HujingWeb/Controllers/Basic/DictCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HujingModel;
using System.Web.Script.Serialization;
using System.Collections;
using IHujingLogic;
using HujingWeb.Filter;

namespace HujingWeb.Controllers
{
    public class DictCodeController : Controller
    {
        IDictCodeLogic codeLogic;
        public DictCodeController(IDictCodeLogic logic)
        {
            codeLogic = logic;
        }

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        [LoginValidateAttribute]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 功能：类别
        /// 日期：add by 2015-12-1
        /// key: 423211xxxyyy
        /// </summary>
        /// <returns></returns>
        public ActionResult TypeAdd()
        {
            return View();
        }



        public ActionResult Add()
        {
            return View();
        }


        public ActionResult Edit(string codetypeid, string codeid)
        {
            if (!string.IsNullOrEmpty(codetypeid))
            {
                DictCodeEntity entityLoad = new DictCodeEntity();
                entityLoad.CodeTypeId = codetypeid;
                entityLoad.CodeId = codeid;
                DictCodeEntity entity = codeLogic.Load(entityLoad);
                return View(entity);
            }
            return View(new DictCodeEntity());
        }


        /// <summary>
        /// 功能：类别集合
        /// 日期：add by 2015-12-1
        /// key: 423211xxxyyy
        /// </summary>
        /// <returns></returns>
        public ActionResult GetTypeList()
        {
            IList<DictCodeEntity> codeEntity = codeLogic.LoadAll(" and codeid='000' ", 10000, 1, "CodeTypeId");
            List<JsonTreeModel> nodes = new List<JsonTreeModel>();
            foreach (var item in codeEntity)
            {
                JsonTreeModel cnode = new JsonTreeModel();
                cnode.id = item.CodeTypeId;
                cnode.name = item.CodeTypeName;
                cnode.pid = "";
                cnode.expanded = true;
                nodes.Add(cnode);
            }
            return Json(nodes);
        }

        public ActionResult GetList(string CodeTypeId, int pageIndex, int pageSize, string sortField, string sortOrder)
        {
            pageIndex = pageIndex + 1;
            string Condition = " and CodeTypeId ='" + CodeTypeId + "' and codeid <> '000' ";
            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "CodeId ";
            }
            IList<DictCodeEntity> roomEntity = codeLogic.LoadAll(Condition, pageSize, pageIndex, sortOrder);
            IDictionary<string, object> dic = new Dictionary<string, object>();
            int count = codeLogic.Count(Condition);
            dic.Add("total", count);
            dic.Add("data", roomEntity);
            return Json(dic);
        }


        /// <summary>
        /// 功能：类别保存
        /// 日期：add by 2015-12-1
        /// key: 423211xabcyyy
        /// </summary>
        /// <returns></returns>
        public ActionResult TypeSave(string CodeTypeId, string CodeTypeName, string Memo)
        {
            string strUserId = HttpContext.ApplicationInstance.Context.Request.Cookies["UserId"].Value;
            DictCodeEntity enty = new DictCodeEntity();
            enty.CodeTypeId = CodeTypeId;
            enty.CodeTypeName = CodeTypeName;
            enty.Memo = Memo;
            enty.CodeId = "000";
            enty.CodeName = "";
            enty.CreateDate = DateTime.Now;
            enty.CreateUser = strUserId;
            bool save = codeLogic.Save(enty);
            if (save == true)
            {
                return Json("ok");
            }
            else
            {
                return Json("no");
            }
        }


        /// <summary>
        /// 功能：字典保存
        /// 日期：add by 2015-12-22
        /// key: 423214xabcyyy
        /// <param name="CodeTypeId"></param>
        /// <param name="CodeTypeName"></param>
        /// <param name="CodeId"></param>
        /// <param name="CodeName"></param>
        /// <param name="Memo"></param>
        /// <returns></returns>
        public ActionResult Save(string CodeTypeId, string CodeTypeName, string CodeId, string CodeName, string Memo)
        {
            string strUserId = HttpContext.ApplicationInstance.Context.Request.Cookies["UserId"].Value;
            DictCodeEntity enty = new DictCodeEntity();
            enty.CreateUser = strUserId;
            enty.CodeTypeId = CodeTypeId;
            enty.CodeTypeName = CodeTypeName;
            enty.Memo = Memo;
            enty.CodeId = CodeId;
            enty.CodeName = CodeName;
            enty.CreateDate = DateTime.Now;
            enty.Flag = false;
            bool save = codeLogic.Save(enty);
            if (save == true)
            {
                return Json("ok");
            }
            else
            {
                return Json("no");
            }
        }

        public ActionResult Update(DictCodeEntity dictCode)
        {
            bool save = codeLogic.Update(dictCode);
            if (save == true)
            {
                return Json("ok");
            }
            else
            {
                return Json("no");
            }
        }


        public ActionResult Delete(string CodeTypeId, string CodeId)
        {
            DictCodeEntity entiy = new DictCodeEntity();
            entiy.CodeTypeId = CodeTypeId;
            entiy.CodeId = CodeId;
            bool isOk = codeLogic.Delete(entiy);
            string result = (isOk == true ? "ok" : "no");
            return Json(result);
        }


        public ActionResult GetCommonDictCode(string codeType)
        {
            IList<DictCodeEntity> codList = new List<DictCodeEntity>();

           string  Condition = " and codeid <> '000'  and codetypeid = '" + codeType + "'";

            codList = codeLogic.LoadAll(Condition,99,1, "codeid");
            return Json(codList, JsonRequestBehavior.AllowGet);
        }
    }
}

HujingWeb/Controllers/Basic/DictItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HujingModel;
using IHujingLogic;
using System.Collections;
using HujingWeb.Filter;
using HujingCommon;

namespace HujingWeb.Controllers
{
    public class DictItemController : Controller
    {

        IDictItemLogic itemLogic;
        ICommonClassLogic commlogic;
        IDictCodeLogic dictCodeLogic;

        public IDictItem_CateLogic  itemCateLogic { get; set; }
        public DictItemController(IDictItemLogic logic, ICommonClassLogic cmLogic, IDictCodeLogic CodeLogic)
        {
            itemLogic = logic;
            commlogic = cmLogic;
            dictCodeLogic = CodeLogic;
        }
        //
        // GET: /DictItem/
        [LoginValidateAttribute]
        public ActionResult Index()
        {
            if (Request.Cookies["UserId"] == null)
            {
                ContentResult content = new ContentResult();
                content.Content = string.Format("<script language='javaScript' type='text/javaScript'>window.parent.window.location.href = '/Home/Login';</script>");
                return content;
            }
            return View();
        }


        /// <summary>
        /// 获取数据
        /// </summary>
        /// <returns></returns>
        public ActionResult GetList(string upperid, int pageIndex, int pageSize, string sortField, string sortOrder)
        {
            string Condition = "";
            pageIndex = pageIndex + 1;
            if (!string.IsNullOrEmpty(upperid))
            {
                Condition += " and CateID= '" + upperid + "'";
            }
            else
            {
                Condition += " and (CateID is null or CateID = '')";
            }
            IList<DictItemEntity> orgEntity = itemLogic.LoadAll(Condition, pageSize, pageIndex, "ItemID");
            IDictionary<string, object> dic = new Dictionary<string, object>();
            int total = itemLogic.Count(Condition);
            dic.Add("total", total);
            dic.Add("data", orgEntity);
            return Json(dic);
        }

        [LoginValidateAttribute]
        public JsonResult Save(IList<DictItemEntity> entity)
        {
            try
            {
                string strCateId = HttpContext.ApplicationInstance.Context.Request.Params["CateId"].ToString();
                string strAddType = HttpContext.ApplicationInstance.Context.Request.Params["addType"].ToString();
                string olditemid = HttpContext.ApplicationInstance.Context.Request.Params["ItemId"].ToString();
                string strUserId = HttpContext.ApplicationInstance.Context.Request.Cookies["UserId"].Value;
                string Condition = "";
                Hashtable dt = new Hashtable();

                foreach (DictItemEntity item in entity)
                {
                    if (dt.Contains(item.ItemName))
                    {
                        string json = JsonHelper.RtnJson("300", item.ItemName + "已经存在！");
                        return Json(json);
                    }
                    else
                    {
                        dt.Add(item.ItemName, item.ItemName);
                    }

                    if (strAddType == "Add")
                    {
                        Condition += " and itemname='" + item.ItemName + "'";
                    }
                    else
                    {
                        Condition = " and itemid != '" + olditemid + "' and itemname='" + item.ItemName + "'";
                    }
                    int itemCount = itemLogic.Count(Condition);
                    if (itemCount > 0)
                    {
                        string json = JsonHelper.RtnJson("300", item.ItemName + "已经存在！");
                        return Json(json);
                    }
                }
     
                for (int i = 0; i < entity.Count; i++)
                {
                    if (strAddType == "Add")
                    {
                        entity[i].ItemID = strUserId + "-ItemId-" + DateTime.Now.ToString("yyMMddHHmmssfff") + i.ToString();
                    }
      
                    entity[i].CateID = strCateId;
                    entity[i].CreateDate = DateTime.Now;
                    entity[i].CreateUser = strUserId;
                    DictCodeEntity codeEntity = new DictCodeEntity();
                    codeEntity.CodeTypeId = DictCodeTypeClass.UnitType;
                    codeEntity.CodeId = entity[i].UnitTypeId;
                    DictCodeEntity entity2 = dictCodeLogic.Load(codeEntity);
                    if (entity2 != null)
                    {
                        entity[i].UnitName = entity2.CodeName;
                    }
                    //entity[i].UnitName = entity[i].UnitTypeId;
                }

                bool isOk = false;
                if (strAddType == "Add")
                {
                    isOk = itemLogic.SaveList(entity);
                }
                else
                {
                    //if (entity[0].ItemID != olditemid)
                    //{
                    //    itemLogic.Delete(olditemid);
                    //    isOk = itemLogic.SaveList(entity);
                    //}
                    //else
                    //{
                        entity[0].UpdateDate = DateTime.Now;
                        entity[0].UpdateUser = strUserId;
                        isOk = itemLogic.Update(entity[0]);
                    //}
                }

                if (isOk == true)
                {
                    string strjson = JsonHelper.RtnJson("100", "");
                    return Json(strjson);
                }
                else
                {
                    string strjson = JsonHelper.RtnJson("300", "保存失败");
                    return Json(strjson);
                }
            }
            catch (Exception ex)
            {
                string strjson = JsonHelper.RtnJson("300", ex.Message);
                return Json(strjson);
            }
        }


        public ActionResult Delete(string ItemIds)
        {
            bool isOk = itemLogic.Delete(ItemIds);
            string result = (isOk == true ? "ok" : "no");
            return Json(result);
        }

        public ActionResult GetUnitType()
        {
            IList<DictCodeEntity> codList = new List<DictCodeEntity>();
            codList = commlogic.GetDictCodeList(DictCodeTypeClass.UnitType);
            return Json(codList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetItemListByFloor(string floorid)
        {
            IList<DictItemEntity> orgEntity = itemLogic.LoadAllByFloorId(floorid);
            IDictionary<string, object> dic = new Dictionary<string, object>();
            int total = orgEntity.Count();
            dic.Add("total", total);
            dic.Add("data", orgEntity);
            return Json(dic);
        }

        /// <summary>
        /// 获取数据
        /// </summary>
        /// <returns></returns>
        public ActionResult GetDictItemList(string inputStr, string typename)
        {
            string Condition = "";
            string catetypeid = "";
            //if (!string.IsNullOrEmpty(typename))
            //{
            //    Condition += " and CateName == '%" + typename + "%'";
            //    IList<DictItem_CateEntity> cateType = itemCateLogic.LoadAll(Condition, 10, 1, "CreateDate");
            //    if ((cateType != null) && (cateType.Count > 0))
            //    {
            //        catetypeid = cateType[0].CateId;
            //    }
            //}


            Condition = "";
            if (!string.IsNullOrEmpty(catetypeid))
            {
                Condition += " and CateID = '" + catetypeid + "'";
            }
            if (!string.IsNullOrEmpty(inputStr))
            {
                Condition += " and ((InputStr like '%" + inputStr + "%') or (itemname like '%"+ inputStr + "%'))";
            }


            IList<DictItemEntity> itemsList = itemLogic.LoadAll(Condition, 10, 1, "ItemName");

            return Json(itemsList);
        }


        public ActionResult GetDictItem_CateList(string codeType)
        {
            IList<DictItem_CateEntity> itemList = itemCateLogic.LoadAll("", 11, 1, "CateID");
            return Json(itemList, JsonRequestBehavior.AllowGet);
        }
    }
}

HujingWeb/Views/Basic/ScheItemDate/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = null;
}
<head>
    <script src="~/Scripts/MiniUI/scripts/boot.js" type="text/javascript"></script>
    <script src="~/Scripts/MiniUI/core.js" type="text/javascript"></script>

</head>

<body>

    <form id="frmSche" method="post" action="">

        <fieldset id="fd1" style="width:92%; height:50px">
            <legend><span>项目排班</span></legend>
            <div class="fieldset-body">
                <div style="float:left; margin-left: 5px">
                    排班日期:
                </div>
                <div style="float:left;margin-left: 5px">
                    <input id="ScheDate" name="ScheDate" class="mini-datepicker" style="width: 120px;" required="true" />
                </div>

                <div id="divType" style="float: left; margin-left: 105px">
                    午别:
                </div>
                <div id="divType2" style="float: left; margin-left: 5px">
                    <input id="TypeCode" name="TypeCode" class="mini-combobox" style="width: 120px" valuefield="CodeId" textfield="CodeName" url='@Url.Action("GetCommonDictCode", "DictCode", new { codeType = @HujingCommon.DictCodeTypeClass.Wubie })' required="true" emptytext="请选择" />
                </div>

                @*<div id="divType" style="float: left; margin-left: 105px">
                        菜单类别:
                    </div>
                    <div id="divType2" style="float: left; margin-left: 5px">
                        <input id="ScheType" name="ScheType" class="mini-combobox" style="width: 120px" valuefield="CateID" textfield="CateName"
                               url='@Url.Action("GetDictItem_CateList", "DictItem")' required="true" emptytext="请选择" />
                    </div>*@
            </div>
        </fieldset>


        <fieldset id="fd1" style="width: 430px; height: 342px">
            <legend><span>选择项目</span></legend>
            <div class="fieldset-body">
                <div style="padding:5px;">
                    <input type="hidden" id="hdCateType" value="荤菜" />
                    <div style="width:680px;">
                        <div class="mini-toolbar" style="border-bottom:0;padding:0px;">
                            <table>
                                <tr>
                                    <td style="width:100%;">
                                        <a class="mini-button" iconcls="icon-add" onclick="addRow()" plain="true" tooltip="增加">增加</a><span class="separator"></span>
                                        <a class="mini-button" iconcls="icon-remove" onclick="removeRow()" plain="true">删除</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div id="grid1" class="mini-datagrid" style="width:680px;height:290px;"
                         idfield="MaItemId"
                         allowresize="true" allowcellselect="true"
                         allowcelledit="true" editnextonenterkey="true" editnextrowcell="true"
                         showpager="false">
                        <div property="columns">
                            <div type="indexcolumn"></div>
                            <div field="InputStr" align="center" width="60" headeralign="center" allowsort="false">
                                助记符
                                <div id="SelType" name="SelType" class="mini-autocomplete" style="width:250px;" property="editor" url="@Url.Action("GetDictItemList","DictItem")"
                                     popupwidth="600" value="" text="" textfield="InputStr" valuefield="InputStr" searchfield="inputStr" onvaluechanged="RefreshCateItem">
                                    <div property="columns">
                                        <div header="助记符" field="InputStr" width="30"></div>
                                        <div header="项目编码" field="ItemID"></div>
                                        <div header="项目名称" field="ItemName"></div>
                                        <div header="单位" field="UnitName"></div>
                                        <div header="零售价" field="SalesPrice"></div>
                                    </div>
                                </div>
                            </div>
                            <div name="ItemID" field="ItemID" width="80" headeralign="center" allowsort="false" visible="false">
                                项目编码
                            </div>
                            <div name="ItemName" field="ItemName" width="80" headeralign="center" allowsort="false">
                                项目名称
                            </div>
                            <div name="UnitName" align="center" field="UnitName" width="40" headeralign="center" allowsort="false">
                                单位
                            </div>
                            <div field="SalesPrice" align="right" width="60" headeralign="center" allowsort="false">零售价</div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <div style="text-align:center;padding:10px;">
            <a class="mini-button" onclick="SaveData" style="width:60px;margin-right:20px;">确定</a>
            <a class="mini-button" onclick="onCancel" style="width:60px;">取消</a>
        </div>

    </form>
    <script>
    mini.parse();
    var grid;
    var form = new mini.Form("frmSche");
    var gridSel;
    $(document).ready(function () {
        grid = mini.get("grid1");
        gridSel = mini.get("SelType");
    });


    function RefreshCateItem(e) {
          var item = e.selected;
            var row = grid.getSelected();
            item.ItemID = item.ItemID;
            item.SalesPrice = item.SalesPrice;
            grid.updateRow(row, item);
    }

    function addRow() {
        var newRow = {};
        grid.addRow(newRow, 0);
        //grid.select(grid.getRow(0));
        //grid.beginEditCell();
    }

    function removeRow() {
        var rows = grid.getSelecteds();
        if (rows.length > 0) {
            grid.removeRows(rows, true);
        }
    }


    //grid.on("celleditenter", function (e) {
    //    var index = grid.indexOf(e.record);
    //    if (index == grid.getData().length - 1) {
    //        var row = {};
    //        grid.addRow(row);
    //    }
    //});

    function onValueChanged(e) {
        var item = e.selected;
        var row = grid.getSelected();
        item.SalesAmount = item.SalesPrice;
        grid.updateRow(row, item);
    }

    function SaveData() {
        form.validate();
        if (form.isValid() == false) return;
        $.ajax({
            url: "@Url.Action("SaveData", "ScheItemDate")",
            type: 'post',
            dataType: "json",
            contentType: 'application/json',
            data: mini.encode({
                head: form.getData(),
                items: grid.getChanges()
            }),
            cache: false,
            success: function (text) {
                if (text) {
                    window.CloseOwnerWindow("save");
                } else {
                    mini.showTips({
                        content: "保存失败！", state: "warning", x: "center", y: "top", timeout: 3000
                    });
                    return;
                }

            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.responseText);
                CloseWindow();
            }
        });
    }


    </script>

</body>

HujingWeb/Views/Basic/ScheItemDate/Index.cshtml
@{
    ViewBag.Title = "项目排班";
    Layout = null;
}
<head>
    <script src="~/Scripts/MiniUI/scripts/boot.js" type="text/javascript"></script>
    <script src="~/Scripts/MiniUI/core.js" type="text/javascript"></script>
    <script type="text/javascript">
        var grid;
        $(document).ready(function () {
            mini.parse();
            grid = mini.get("grid1");

            //            grid.load();
            var myDate = new Date();
            var strDate = myDate.getFullYear() + "-" + (myDate.getMonth() + 1) + "-" + myDate.getDate();

            var strEndDate = myDate.getFullYear() + "-" + (myDate.getMonth() + 2) + "-" + myDate.getDate();
            mini.getbyName("dateBegin").setValue(strDate);
            mini.getbyName("dateEnd").setValue(strEndDate);
            Search();
        });


        function AddRow() {
            var url = '@Url.Action("Add")';
            mini.open({
                url: url,
                title: "菜单排班", width: 750, height: 550,
                onload: function () {
                    var iframe = this.getIFrameEl();
                    var data = { action: "new" };
                },
                ondestroy: function (action) {
                    if (action == "save") {
                        Search();
                    }
                }
            });
        }


        function Search() {
            var DateBegin = mini.getbyName("dateBegin").text;
            var DateEnd = mini.getbyName("dateEnd").text;
            grid.load({ dateBegin: DateBegin, dateEnd: DateEnd});
        }

        function onKeyEnter(e) {
            Search();
        }

        var StatusList = [{ id: '0', text: '咨询' }, { id: '1', text: '试住' }, { id: '3', text: '入住' }];
        function OnStatusChange(e) {
            for (var i = 0, l = StatusList.length; i < l; i++) {
                var g = StatusList[i];
                if (g.id == e.value) return g.text;
            }
            return "";
        }

    function Remove() {
        var rows = grid.getSelecteds();
        if (rows.length <= 0) {
            mini.showTips({ content: "请选择需要删除的数据！", state: "warning", x: "center", y: "top", timeout: 3000 });
            return;
        }

        var ids = [];
        for (var i = 0, l = rows.length; i < l; i++) {
            var r = rows[i];
            ids.push(r.SchId);
        }
        var id = ids.join(',');
        mini.confirm("确定删除此用户信息吗？", "确定信息",
            function (action) {
                if (action == "ok") {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("Delete")',
                        data: { "SchIds": id },
                        cache: false,
                        success: function (result) {
                            if (result) {
                                mini.showTips({ content: "操作成功！", state: "success", x: "center", y: "top", timeout: 3000 });
                                grid.load();
                            }
                            else {
                                mini.showTips({ content: "操作失败！", state: "danger", x: "center", y: "top", timeout: 3000 });
                            }
                        }
                    });
                }
            }
        );
        }


        var wubies = [{ id: "01", text: '早餐' }, { id:"02", text: '午餐' }, { id:"03", text: '晚餐' }];
        function OnWubieChange(e) {
            for (var i = 0, l = wubies.length; i < l; i++) {
                var g = wubies[i];
                if (g.id == e.value) return g.text;
            }
            return "";
        }
    </script>
</head>
<body>
    <div>
        <ul class="mnbreadcrumb">
            <li>
                <a href="#">基本信息</a> <span class="divider"></span>
            </li>
            <li>
                <a href="#">菜单排班</a>
            </li>
        </ul>
    </div>


    <div showcollapsebutton="true">
        <div>
            <fieldset id="fd1" style="width:98%; height:85px">
                <legend><span>菜单排班</span></legend>
                <div class="fieldset-body">
                    <div>
                        <div style="float: left; margin-left: 30px">
                            开始日期:
                        </div>
                        <div style="float: left; margin-left: 5px">
                            <input id="dateBegin" name="dateBegin" class="mini-datepicker" style="width:120px" value="2000-01-01" />
                        </div>

                        <div style="float: left; margin-left: 5px">
                            项目名称:
                        </div>
                        <div style="float: left; margin-left: 5px">
                            <input id="PatiName" name="PatiName" class="mini-textbox" style="width:120px" />
                        </div>
                    </div>
                    <div style="clear: both; height: 5px">
                    </div>
                    <div>
                        <div style="float: left; margin-left: 30px">
                            结束日期:
                        </div>
                        <div style="float: left; margin-left: 5px">
                            <input id="dateEnd" name="dateEnd" class="mini-datepicker" style="width:120px" value="2000-01-01" />
                        </div>
                    </div>
                    <div style="position: absolute; left: 450px; top: 100px">
                        <a class="mini-button" onclick="Search()">查询</a>
                    </div>
                </div>
            </fieldset>
        </div>
        <div style="clear: both; margin-top: 5px; width: 100%; height: 30px">
            <div class="mini-toolbar" style="border-bottom: 0; padding: 0px;">
                <table style="width: 100%;">
                    <tr>
                        <td style="width: 100%;">
                            <a class="mini-button" iconcls="icon-add" onclick="AddRow()">增加</a><span class="separator"></span>
                            <a id="btnDelete" class="mini-button" iconcls="icon-remove" plain="true" onclick="Remove()">删除</a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div id="grid1" class="mini-datagrid" style="width: 100%; height: 63%;" allowresize="true"
             url="@Url.Action("GetList")" idfield="SchId" pagesize="15" multiselect="true">
            <div property="columns">
                <div type="checkcolumn" width="25">
                </div>
                <div field="ItemID" width="80" headeralign="center" align="center" allowsort="true" visible="false">
                    项目编号
                </div>
                <div field="ItemName" width="80" headeralign="center" align="center" allowsort="true">
                    项目名称
                </div>
                <div field="UnitName" width="40" headeralign="center" align="center" allowsort="true">
                    规格
                </div>
                <div field="Price" width="40" headeralign="center" align="center" allowsort="true">
                    价格
                </div>
                <div field="ScheDate" width="80" headeralign="center" align="center" allowsort="true" dateformat="yyyy-MM-dd">
                    排版日期
                </div>
                <div field="TypeCode" width="80" headeralign="center" align="center" allowsort="true"  renderer="OnWubieChange">
                    午别
                </div>
            </div>
        </div>
    </div>
</body>