HujingWeb/Controllers/StaticalReportController.cs
using HujingAccess.ChargeManager;
using HujingModel;
using HujingModel.ViewModel;
using IHujingLogic;
using IHujingLogic.UserOrder;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HujingWeb.Controllers
{
    public class StaticalReportController : Controller
    {
        public IPatiInBillItemLogic billitemLogic { get; set; }
        public IUserInfoLogic userLogic { get; set; }

        public IOrderDinnerLogic userOrderLogic { get; set; }
        //
        // GET: /StaticalReport/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult UserFeeDetail()
        {
            return View();
        }


        public ActionResult UserFeeTotal()
        {
            return View();
        }


        public ActionResult UserMonthFeeTotal()
        {
            return View();
        }



        public ActionResult UserFeeList(string userName, string dateBegin, string dateEnd, int? pageIndex, int? pageSize, string sortField, string sortOrder)
        {
            pageIndex = pageIndex + 1;

            if (pageSize == null)
            {
                pageSize = 15;
            }

            string Condition = " and 1=1";
            if (!string.IsNullOrEmpty(userName))
            {
                Condition += " and ( UserName like '%" + userName + "%') ";
            }
            if (!string.IsNullOrEmpty(dateBegin))
            {
                Condition += " and PatiInBillItem.CreateDate >= '" + DateTime.Parse(dateBegin).ToString("yyyy-MM-dd 00:00:00") + "'";
            }
            if (!string.IsNullOrEmpty(dateEnd))
            {
                Condition += " and PatiInBillItem.CreateDate <= '" + DateTime.Parse(dateEnd).ToString("yyyy-MM-dd 23:59:59") + "'";
            }

            if (string.IsNullOrEmpty(sortField))
            {
                sortField = "CreateDate";
            }
            if (string.IsNullOrEmpty(sortOrder))
            {
                sortOrder = "desc";
            }

            IList<PatiInBillItemEntity> lstBillItem = billitemLogic.LoadAllBillItem(Condition, pageSize.Value, pageIndex.Value, sortField, sortOrder);
            foreach (var item in lstBillItem)
            {
                UserInfoEntity userEntity = userLogic.Load(item.UserId);
                item.UserName = userEntity.UserName;
                item.SexName = userEntity.Sex == "0" ? "男" : "女";
            }

            IDictionary<string, object> dic = new Dictionary<string, object>();
            int count = billitemLogic.Count(Condition);
            dic.Add("total", count);
            dic.Add("data", lstBillItem);
            return Json(dic, JsonRequestBehavior.AllowGet);
        }

        public FileResult Export_UserFeeDetail_Excel(string userName, string dateBegin, string dateEnd)
        {
            string Condition = " and 1=1";
            if (!string.IsNullOrEmpty(userName))
            {
                Condition += " and ( UserName like '%" + userName + "%') ";
            }
            if (!string.IsNullOrEmpty(dateBegin))
            {
                Condition += " and PatiInBillItem.CreateDate >= '" + DateTime.Parse(dateBegin).ToString("yyyy-MM-dd 00:00:00") + "'";
            }
            if (!string.IsNullOrEmpty(dateEnd))
            {
                Condition += " and PatiInBillItem.CreateDate <= '" + DateTime.Parse(dateEnd).ToString("yyyy-MM-dd 23:59:59") + "'";
            }

            string sortField = "CreateDate";

            string sortOrder = "desc";


            IList<PatiInBillItemEntity> lstBillItem = billitemLogic.LoadAllBillItem(Condition, 9999, 1, sortField, sortOrder);
            foreach (var item in lstBillItem)
            {
                UserInfoEntity userEntity = userLogic.Load(item.UserId);
                item.UserName = userEntity.UserName;
                item.SexName = userEntity.Sex == "0" ? "男" : "女";
            }

            //创建Excel文件的对象
            NPOI.HSSF.UserModel.HSSFWorkbook book = new NPOI.HSSF.UserModel.HSSFWorkbook();
            //添加一个sheet
            NPOI.SS.UserModel.ISheet sheet1 = book.CreateSheet("Sheet1");
            //获取list数据
            // List<modelList> listRainInfo = m_BLL.GetSchoolListAATQ(schoolname);
            //给sheet1添加第一行的头部标题
            NPOI.SS.UserModel.IRow row1 = sheet1.CreateRow(0);
            row1.CreateCell(0).SetCellValue("员工姓名");
            row1.CreateCell(1).SetCellValue("员工性别");
            row1.CreateCell(2).SetCellValue("就餐日期");
            row1.CreateCell(3).SetCellValue("午别");
            row1.CreateCell(4).SetCellValue("金额");
            row1.CreateCell(5).SetCellValue("创建日期");
            row1.CreateCell(6).SetCellValue("创建人");
            //将数据逐步写入sheet1各个行
            for (int i = 0; i < lstBillItem.Count; i++)
            {
                NPOI.SS.UserModel.IRow rowtemp = sheet1.CreateRow(i + 1);
                rowtemp.CreateCell(0).SetCellValue(lstBillItem[i].UserName.ToString());
                rowtemp.CreateCell(1).SetCellValue(lstBillItem[i].SexName.ToString());
                rowtemp.CreateCell(2).SetCellValue(lstBillItem[i].CreateDate.ToString());
                if(lstBillItem[i].TypeCode=="01")
                {
                    rowtemp.CreateCell(3).SetCellValue("早餐");
                }
                else if (lstBillItem[i].TypeCode == "02")
                {
                    rowtemp.CreateCell(3).SetCellValue("午餐");
                }
                else if (lstBillItem[i].TypeCode == "03")
                {
                    rowtemp.CreateCell(3).SetCellValue("晚餐");
                }
                rowtemp.CreateCell(4).SetCellValue(lstBillItem[i].Amount.ToString());
                rowtemp.CreateCell(5).SetCellValue(lstBillItem[i].CreateDate.ToString());
                rowtemp.CreateCell(6).SetCellValue(lstBillItem[i].CreateUser.ToString());
            }
            // 写入到客户端 
            System.IO.MemoryStream ms = new System.IO.MemoryStream();
            book.Write(ms);
            ms.Seek(0, SeekOrigin.Begin);
            return File(ms, "application/vnd.ms-excel", DateTime.Now.ToString("yyyyMMddHHmmss") + ".xls");
        }


        public ActionResult UserFeeDayList(string dateBegin, string dateEnd, int? pageIndex, int? pageSize)
        {
            pageIndex = pageIndex + 1;

            if (pageSize == null)
            {
                pageSize = 15;
            }

            string Condition = " and 1=1";
            if (!string.IsNullOrEmpty(dateBegin))
            {
                Condition += " and PatiInBillItem.CreateDate >= '" + DateTime.Parse(dateBegin).ToString("yyyy-MM-dd 00:00:00") + "'";
            }
            if (!string.IsNullOrEmpty(dateEnd))
            {
                Condition += " and PatiInBillItem.CreateDate <= '" + DateTime.Parse(dateEnd).ToString("yyyy-MM-dd 23:59:59") + "'";
            }

            IList<UserBillTotal> billTotal = new List<UserBillTotal>();
            DataTable lstBillItem = billitemLogic.GetPersonBillTypeAmount(Condition, pageSize.Value, pageIndex.Value, "", "");
            if (lstBillItem != null && lstBillItem.Rows.Count > 0)
            {
                foreach (DataRow drNew in lstBillItem.Rows)
                {
                    UserBillTotal item = new UserBillTotal();
                    item.BillDate = drNew[0].ToString();
                    item.TotalAmount = decimal.Parse(drNew[1].ToString());
                    billTotal.Add(item);
                }
            }

            IDictionary<string, object> dic = new Dictionary<string, object>();
            int count = billTotal.Count();
            dic.Add("total", count);
            dic.Add("data", billTotal);
            return Json(dic, JsonRequestBehavior.AllowGet);
        }

        public FileResult ExportExcel(string dateBegin, string dateEnd)
        {
            string Condition = " and 1=1";
            if (!string.IsNullOrEmpty(dateBegin))
            {
                Condition += " and PatiInBillItem.CreateDate >= '" + DateTime.Parse(dateBegin).ToString("yyyy-MM-dd 00:00:00") + "'";
            }
            if (!string.IsNullOrEmpty(dateEnd))
            {
                Condition += " and PatiInBillItem.CreateDate <= '" + DateTime.Parse(dateEnd).ToString("yyyy-MM-dd 23:59:59") + "'";
            }

            IList<UserBillTotal> billTotal = new List<UserBillTotal>();
            DataTable lstBillItem = billitemLogic.GetPersonBillTypeAmount(Condition, 9999, 1, "", "");
            if (lstBillItem != null && lstBillItem.Rows.Count > 0)
            {
                foreach (DataRow drNew in lstBillItem.Rows)
                {
                    UserBillTotal item = new UserBillTotal();
                    item.BillDate = drNew[0].ToString();
                    item.TotalAmount = decimal.Parse(drNew[1].ToString());
                    billTotal.Add(item);
                }
            }
            //创建Excel文件的对象
            NPOI.HSSF.UserModel.HSSFWorkbook book = new NPOI.HSSF.UserModel.HSSFWorkbook();
            //添加一个sheet
            NPOI.SS.UserModel.ISheet sheet1 = book.CreateSheet("Sheet1");
            //获取list数据
            // List<modelList> listRainInfo = m_BLL.GetSchoolListAATQ(schoolname);
            //给sheet1添加第一行的头部标题
            NPOI.SS.UserModel.IRow row1 = sheet1.CreateRow(0);
            row1.CreateCell(0).SetCellValue("就餐日期");
            row1.CreateCell(1).SetCellValue("金额");
            //将数据逐步写入sheet1各个行
            for (int i = 0; i < billTotal.Count; i++)
            {
                NPOI.SS.UserModel.IRow rowtemp = sheet1.CreateRow(i + 1);
                rowtemp.CreateCell(0).SetCellValue(billTotal[i].BillDate.ToString());
                rowtemp.CreateCell(1).SetCellValue(billTotal[i].TotalAmount.ToString());
            }
            // 写入到客户端 

HujingWeb/Views/StaticalReport/EatNoUserOrder.cshtml
@{
    ViewBag.Title = "消费报表";
}
<head>
    <script src="~/Scripts/MiniUI/scripts/boot.js" type="text/javascript"></script>
    <script src="~/Scripts/MiniUI/core.js" type="text/javascript"></script>
    <script type="text/javascript">
        var grid;
        $(document).ready(function () {
            mini.parse();
            grid = mini.get("gridFeel");
            grid.load();
        });


        function search() {
            //var strTypeId = mini.get("selTypeId").getValue();
            var username = mini.get("UserName").getValue();
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            // var patiname = $("#PatiName").val();
            grid.load({ userName: username, dateBegin: datebegin, dateEnd: dateend});
        }
        function onKeyEnter(e) {
            search();
        }


        var Genders = [{ id: 0, text: '男' }, { id: 1, text: '女' }];
        function OnSexChange(e) {
            for (var i = 0, l = Genders.length; i < l; i++) {
                var g = Genders[i];
                if (g.id == e.value) return g.text;
            }
            return "";
        }

        var wubies = [{ id: "01", text: '早餐' }, { id: "02", text: '午餐' }, { id: "03", text: '晚餐' }];
        function OnWubieChange(e) {
            for (var i = 0, l = wubies.length; i < l; i++) {
                var g = wubies[i];
                if (g.id == e.value) return g.text;
            }
            return "";
        }


        function Export()
        {
            var username = mini.get("UserName").getValue();
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            window.location.href = '@Url.Action("Export_EatNoUserOrder_Excel")' + "?userName=" + username+"&dateBegin=" + datebegin + "&dateEnd=" + dateend;
        }

    </script>
</head>
<div>
    <ul class="mnbreadcrumb">
        <li>
            <a href="#">数据查询</a> <span class="divider"></span>
        </li>
        <li>
            <a href="#">就餐未预约</a>
        </li>
    </ul>
</div>
<div showcollapsebutton="true">
    <div style="width: 520px; padding: 10px; height: 80px; border: 1px gray solid">
        <div>
            <div style="float: left; margin-left: 5px">
                员工姓名:
            </div>
            <div style="float: left; margin-left: 5px">
                <input id="UserName" name="UserName" class="mini-textbox" style="width: 120px" required="true" />
            </div>
            <div style="float: left; margin-left: 26px">
                就餐日期:
            </div>
            <div style="float: left; margin-left: 5px">
                <input id="dateBegin" class="mini-datepicker" style="width: 120px;" />
            </div>
        </div>
        <div style="clear: both; height: 15px">
        </div>
        <div>
            <div style="margin-left: 265px">
                <input id="dateEnd" class="mini-datepicker" style="width: 120px;" />
            </div>
        </div>
        <div style="position: absolute; left: 450px; top: 110px">
            <a class="mini-button" onclick="search()">查询</a>
        </div>
    </div>

    <div style="clear: both; margin-top: 5px; width: 100%; height: 30px">
        <div class="mini-toolbar" style="border-bottom: 0; padding: 0px;">
            <table style="width: 100%;">
                <tr>
                    <td style="width: 100%;">
                        <a class="mini-button" iconcls="icon-export" onclick="Export()">导出</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div id="gridFeel" class="mini-datagrid" style="width: 100%; height: 65%;" allowresize="true"
         url="@Url.Action("GetEatNoUserOrderList","StaticalReport")" idfield="BillItemId" pagesize="1500" multiselect="false">
        <div property="columns">
            <div type="checkcolumn" width="25">
            </div>
            <div field="CreateDate" width="70" headeralign="center" align="center" allowsort="true" dateformat="yyyy-MM-dd">
                就餐日期
            </div>
            <div field="UserId" width="80" headeralign="center" align="center" allowsort="true">
                员工工号
            </div>
            <div field="UserName" width="80" headeralign="center" align="center" allowsort="true">
                员工姓名
            </div>
            <div field="TypeCode" width="70" headeralign="center" align="center" allowsort="true" renderer="OnWubieChange">
                午别
            </div>
            <div field="Amount" width="80" headeralign="center" align="center" allowsort="true">
                金额
            </div>
        </div>
    </div>
</div>

HujingWeb/Views/StaticalReport/UserFeeDetail.cshtml
@{
    ViewBag.Title = "消费报表";
}
<head>
    <script src="~/Scripts/MiniUI/scripts/boot.js" type="text/javascript"></script>
    <script src="~/Scripts/MiniUI/core.js" type="text/javascript"></script>
    <script type="text/javascript">
        var grid;
        $(document).ready(function () {
            mini.parse();
            grid = mini.get("gridFeel");
            grid.load();
        });


        function search() {
            //var strTypeId = mini.get("selTypeId").getValue();
            var username = mini.get("UserName").getValue();
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            // var patiname = $("#PatiName").val();
            grid.load({ userName: username, dateBegin: datebegin, dateEnd: dateend});
        }
        function onKeyEnter(e) {
            search();
        }


        var Genders = [{ id: 0, text: '男' }, { id: 1, text: '女' }];
        function OnSexChange(e) {
            for (var i = 0, l = Genders.length; i < l; i++) {
                var g = Genders[i];
                if (g.id == e.value) return g.text;
            }
            return "";
        }

        var wubies = [{ id: "01", text: '早餐' }, { id: "02", text: '午餐' }, { id: "03", text: '晚餐' }];
        function OnWubieChange(e) {
            for (var i = 0, l = wubies.length; i < l; i++) {
                var g = wubies[i];
                if (g.id == e.value) return g.text;
            }
            return "";
        }


        function Export()
        {
            var username = mini.get("UserName").getValue();
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            window.location.href = '@Url.Action("Export_UserFeeDetail_Excel")' + "?userName=" + username+"&dateBegin=" + datebegin + "&dateEnd=" + dateend;
        }

    </script>
</head>
<div>
    <ul class="mnbreadcrumb">
        <li>
            <a href="#">数据查询</a> <span class="divider"></span>
        </li>
        <li>
            <a href="#">员工用餐</a>
        </li>
    </ul>
</div>
<div showcollapsebutton="true">
    <div style="width: 520px; padding: 10px; height: 80px; border: 1px gray solid">
        <div>
            <div style="float: left; margin-left: 5px">
                员工姓名:
            </div>
            <div style="float: left; margin-left: 5px">
                <input id="UserName" name="UserName" class="mini-textbox" style="width: 120px" required="true" />
            </div>
            <div style="float: left; margin-left: 26px">
                就餐日期:
            </div>
            <div style="float: left; margin-left: 5px">
                <input id="dateBegin" class="mini-datepicker" style="width: 120px;" />
            </div>
        </div>
        <div style="clear: both; height: 15px">
        </div>
        <div>
            <div style="margin-left: 265px">
                <input id="dateEnd" class="mini-datepicker" style="width: 120px;" />
            </div>
        </div>
        <div style="position: absolute; left: 450px; top: 110px">
            <a class="mini-button" onclick="search()">查询</a>
        </div>
    </div>

    <div style="clear: both; margin-top: 5px; width: 100%; height: 30px">
        <div class="mini-toolbar" style="border-bottom: 0; padding: 0px;">
            <table style="width: 100%;">
                <tr>
                    <td style="width: 100%;">
                        <a class="mini-button" iconcls="icon-export" onclick="Export()">导出</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div id="gridFeel" class="mini-datagrid" style="width: 100%; height: 65%;" allowresize="true"
         url="@Url.Action("UserFeeList")" idfield="BillItemId" pagesize="15" multiselect="false">
        <div property="columns">
            <div type="checkcolumn" width="25">
            </div>
            <div field="UserName" width="80" headeralign="center" align="center" allowsort="true">
                员工姓名
            </div>
            <div field="SexName" width="80" headeralign="center" align="center" allowsort="true">
                员工性别
            </div>
            <div field="CreateDate" width="70" headeralign="center" align="center" allowsort="true" dateformat="yyyy-MM-dd">
                就餐日期
            </div>
            <div field="TypeCode" width="70" headeralign="center" align="center" allowsort="true" renderer="OnWubieChange">
                午别
            </div>
            <div field="Amount" width="70" headeralign="center" align="center" allowsort="true">
                金额
            </div>
            <div field="CreateDate" width="70" headeralign="center" align="center" allowsort="true" dateformat="yyyy-MM-dd">
                创建日期
            </div>
            <div field="CreateUser" width="70" headeralign="center" align="center" allowsort="true">
                创建人
            </div>
        </div>
    </div>
</div>

HujingWeb/Views/StaticalReport/UserFeeTotal.cshtml
@{
    ViewBag.Title = "消费报表";
}
<head>
    <script src="~/Scripts/MiniUI/scripts/boot.js" type="text/javascript"></script>
    <script src="~/Scripts/MiniUI/core.js" type="text/javascript"></script>
    <script type="text/javascript">
        var grid;
        $(document).ready(function () {
            mini.parse();
            grid = mini.get("gridFeel");
            grid.load();
        });


        function search() {
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            grid.load({dateBegin: datebegin, dateEnd: dateend});
        }

        function Export()
        {
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            window.location.href = '@Url.Action("ExportExcel")' + "?dateBegin=" + datebegin + "&dateEnd=" + dateend;
        }

    </script>
</head>
<div>
    <ul class="mnbreadcrumb">
        <li>
            <a href="#">数据查询</a> <span class="divider"></span>
        </li>
        <li>
            <a href="#">员工用餐</a>
        </li>
    </ul>
</div>
<div showcollapsebutton="true">
    <div style="width: 520px; padding: 10px; height:40px; border: 1px gray solid">
        <div>
            <div style="float: left; margin-left: 26px">
                就餐日期:
            </div>
            <div style="float: left; margin-left: 5px">
                <input id="dateBegin" class="mini-datepicker" style="width: 120px;" />
            </div>
            <div style="float: left;margin-left: 26px">
                <input id="dateEnd" class="mini-datepicker" style="width: 120px;" />
            </div>
        </div>
        <div style="position: absolute; left: 400px; top:70px">
            <a class="mini-button" onclick="search()">查询</a>
        </div>
    </div>
    <div style="clear: both; margin-top: 5px; width: 100%; height: 30px">
        <div class="mini-toolbar" style="border-bottom: 0; padding: 0px;">
            <table style="width: 100%;">
                <tr>
                    <td style="width: 100%;">
                        <a class="mini-button" iconcls="icon-export" onclick="Export()">导出</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div id="gridFeel" class="mini-datagrid" style="width: 100%; height: 65%;" allowresize="true"
         url="@Url.Action("UserFeeDayList")" idfield="BillItemId" pagesize="15" multiselect="false">
        <div property="columns">
            <div type="checkcolumn" width="25">
            </div>
            <div field="BillDate" width="70" headeralign="center" align="center" allowsort="true" dateformat="yyyy-MM-dd">
                就餐日期
            </div>
            <div field="TotalAmount" width="70" headeralign="center" align="center" allowsort="true">
                金额
            </div>
        </div>
    </div>
</div>

HujingWeb/Views/StaticalReport/UserMonthFeeTotal.cshtml
@{
    ViewBag.Title = "消费报表";
}
<head>
    <script src="~/Scripts/MiniUI/scripts/boot.js" type="text/javascript"></script>
    <script src="~/Scripts/MiniUI/core.js" type="text/javascript"></script>
    <script type="text/javascript">
        var grid;
        $(document).ready(function () {
            mini.parse();
            grid = mini.get("gridFeel");
            grid.load();
        });


        function search() {
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            // var patiname = $("#PatiName").val();
            grid.load({dateBegin: datebegin, dateEnd: dateend});
        }


    </script>
</head>
<div>
    <ul class="mnbreadcrumb">
        <li>
            <a href="#">数据查询</a> <span class="divider"></span>
        </li>
        <li>
            <a href="#">员工用餐</a>
        </li>
    </ul>
</div>
<div showcollapsebutton="true">
    <div style="width: 520px; padding: 10px; height:40px; border: 1px gray solid">
        <div>
            <div style="float: left; margin-left: 26px">
                就餐日期:
            </div>
            <div style="float: left; margin-left: 5px">
                <input id="dateBegin" class="mini-datepicker" style="width: 120px;" />
            </div>
            <div style="float: left;margin-left: 26px">
                <input id="dateEnd" class="mini-datepicker" style="width: 120px;" />
            </div>
        </div>
        <div style="position: absolute; left: 400px; top:70px">
            <a class="mini-button" onclick="search()">查询</a>
        </div>
    </div>

    <div id="gridFeel" class="mini-datagrid" style="width: 100%; height: 65%;" allowresize="true"
         url="@Url.Action("UserMonthDayList")" idfield="BillItemId" pagesize="15" multiselect="false">
        <div property="columns">
            <div type="checkcolumn" width="25">
            </div>
            <div field="BillDate" width="70" headeralign="center" align="center" allowsort="true" dateformat="yyyy-MM-dd">
                就餐年月
            </div>
            <div field="TotalAmount" width="70" headeralign="center" align="center" allowsort="true">
                金额
            </div>
        </div>
    </div>
</div>

HujingWeb/Views/StaticalReport/UserOrderNoEat.cshtml
@{
    ViewBag.Title = "消费报表";
}
<head>
    <script src="~/Scripts/MiniUI/scripts/boot.js" type="text/javascript"></script>
    <script src="~/Scripts/MiniUI/core.js" type="text/javascript"></script>
    <script type="text/javascript">
        var grid;
        $(document).ready(function () {
            mini.parse();
            grid = mini.get("gridFeel");
            grid.load();
        });


        function search() {
            //var strTypeId = mini.get("selTypeId").getValue();
            var username = mini.get("UserName").getValue();
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            // var patiname = $("#PatiName").val();
            grid.load({ userName: username, dateBegin: datebegin, dateEnd: dateend});
        }
        function onKeyEnter(e) {
            search();
        }


        var Genders = [{ id: 0, text: '男' }, { id: 1, text: '女' }];
        function OnSexChange(e) {
            for (var i = 0, l = Genders.length; i < l; i++) {
                var g = Genders[i];
                if (g.id == e.value) return g.text;
            }
            return "";
        }

        var wubies = [{ id: "01", text: '早餐' }, { id: "02", text: '午餐' }, { id: "03", text: '晚餐' }];
        function OnWubieChange(e) {
            for (var i = 0, l = wubies.length; i < l; i++) {
                var g = wubies[i];
                if (g.id == e.value) return g.text;
            }
            return "";
        }


        function Export()
        {
            var username = mini.get("UserName").getValue();
            var datebegin = mini.get("dateBegin").text;;
            var dateend = mini.get("dateEnd").text;;
            window.location.href = '@Url.Action("Export_UserOrderNoEat_Excel")' + "?userName=" + username+"&dateBegin=" + datebegin + "&dateEnd=" + dateend;
        }

    </script>
</head>
<div>
    <ul class="mnbreadcrumb">
        <li>
            <a href="#">数据查询</a> <span class="divider"></span>
        </li>
        <li>
            <a href="#">预约未就餐</a>
        </li>
    </ul>
</div>
<div showcollapsebutton="true">
    <div style="width: 520px; padding: 10px; height: 80px; border: 1px gray solid">
        <div>
            <div style="float: left; margin-left: 5px">
                员工姓名:
            </div>
            <div style="float: left; margin-left: 5px">
                <input id="UserName" name="UserName" class="mini-textbox" style="width: 120px" required="true" />
            </div>
            <div style="float: left; margin-left: 26px">
                就餐日期:
            </div>
            <div style="float: left; margin-left: 5px">
                <input id="dateBegin" class="mini-datepicker" style="width: 120px;" />
            </div>
        </div>
        <div style="clear: both; height: 15px">
        </div>
        <div>
            <div style="margin-left: 265px">
                <input id="dateEnd" class="mini-datepicker" style="width: 120px;" />
            </div>
        </div>
        <div style="position: absolute; left: 450px; top: 110px">
            <a class="mini-button" onclick="search()">查询</a>
        </div>
    </div>

    <div style="clear: both; margin-top: 5px; width: 100%; height: 30px">
        <div class="mini-toolbar" style="border-bottom: 0; padding: 0px;">
            <table style="width: 100%;">
                <tr>
                    <td style="width: 100%;">
                        <a class="mini-button" iconcls="icon-export" onclick="Export()">导出</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div id="gridFeel" class="mini-datagrid" style="width: 100%; height: 65%;" allowresize="true"
         url="@Url.Action("GetUserOrderNoEatList","StaticalReport")" idfield="BillItemId" pagesize="1500" multiselect="false">
        <div property="columns">
            <div type="checkcolumn" width="25">
            </div>
            <div field="orderDate" width="70" headeralign="center" align="center" allowsort="true" dateformat="yyyy-MM-dd">
                预约日期
            </div>
            <div field="userId" width="80" headeralign="center" align="center" allowsort="true">
                员工工号
            </div>
            <div field="userName" width="80" headeralign="center" align="center" allowsort="true">
                员工姓名
            </div>
            <div field="type" width="70" headeralign="center" align="center" allowsort="true" renderer="OnWubieChange">
                午别
            </div>
            <div field="Quantity" width="70" headeralign="center" align="center" allowsort="true">
                数量
            </div>
        </div>
    </div>
</div>